### ISSUE TITLE
[Question] Can a ClusterClaim be labelled with open-cluster-management.io/hub-managed?

### ISSUE THREAD

**Issue by aushacker** [open-cluster-management-io/open-cluster-management-io.github.io#461]
I'm using Red Hat ACM 2.12 as the hub and have joined a MicroShift spoke. It's working as expected.

My question involves a ClusterClaim that is being created on the spoke:
```
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: ClusterClaim
metadata:
  ...
  labels:
    open-cluster-management.io/hub-managed: ""
    open-cluster-management.io/spoke-only: ""
    velero.io/exclude-from-backup: "true"
  name: name
  ...
spec:
  value: microshift
```

Is the key `open-cluster-management.io/hub-managed` valid and if yes, then where is it documented?
